Adx 407 Clean up restricted code
fjelltopp/unaids_data_specifications pull request #7
Opened 2020-10-08 20:51 UTC by jonathansberry

Ckanext Restricted has been really bugging me for a while. This was set up very early in the project's lifestyle. I've spent a while de coupling it from scheming, cleaning up the UI and the configs.

I have also moved the creation of the restricted json string from a validator to the client side as it is a far cleaner way of working with and debugging the software. This also helps decouple the extension from the scheming extension and create behaviour more inline with restricted tests.

There are a number of related PRS.

2020-10-09 07:22 UTC, jonathansberry commented
I had hoped that dd0c43d28181c74096 would only reflect the config changes, and the later commit would reflect the indentation/formatting changes, sadly my editor seems to have done some crazy stuff automatically. It's more time than it's worth to undo and make neat. There's a test there to make sure I didn't screw up the config change.

2020-10-13 13:16 UTC, tomeksabala approved these changes
LGTM. Please wait with the merge until I finish with the rest of related PRs.

2020-10-13 13:16 UTC, tomeksabala commented on tests/test_data_specs.py
> +        log.warning(pformat(schema.keys()))
log.debug("Schema keys: " + pformat(schema.keys()))

2020-10-13 13:16 UTC, tomeksabala commented on tests/test_data_specs.py
> +        ))
why like this instead of a simpler?:
```
restricted_fields = [field for field in resource_fields if field['field_name'] == 'restricted']
```

2020-10-13 13:19 UTC, tomeksabala requested changes
I've approved the PR by accident. My comments are stated above. I'll repeat them below:
1. I think that log.warning should certainly be fixed to debug. We need to take care of our already messy log output.
2. The 2nd comment for restricted_fields is just for you consideration.

2020-10-13 15:32 UTC, jonathansberry commented on tests/test_data_specs.py
> +        log.warning(pformat(schema.keys()))
Yeah happy to do this.  Something is wrong in the way I'm working with this though... Should I come to trying to fix this test again you can be sure I will just change it back to warning, which raises the question should it be there at all.  The debug and info levels are so full of stuff that it's impossible to see what you need to see there, so I am in the habit of always running tests for logging level warning and just raising what I need to see at that level.

2020-10-13 15:33 UTC, jonathansberry commented on tests/test_data_specs.py
> +        ))
Only that it's a matter of personal taste.  I find the above far more readable, but it's probably what I'm used to.

2020-10-13 15:41 UTC, merged